### PR TITLE
feature(paginate): Adding new feature to search for deleted items wit…

### PR DESCRIPTION
**Pull request by LeonardoDB**
…h soft delete

### CODE REVIEW

**Comment by ppetzold** [comment]
LGTM, ci fails tho due to formatting. you can `npm run format` to fix

**Comment by ppetzold** [comment]
also please describe new config param in README

**Comment by LeonardoDB** [comment]
Thanks for reminding me =), I put this new parameter in the README.

**Review by ppetzold — APPROVED** [review]

**Pull request merged**
