### PR TITLE
fix: isolate where option query

### PR DESCRIPTION
**Pull request by bartosjiri**
An attempt to resolve https://github.com/ppetzold/nestjs-paginate/issues/96.

New additional tests might be needed.

### CODE REVIEW

**Comment by ppetzold** [comment]
Looks good to me.  I wasn't actually aware of this. Feels definitely more intuitive to me as well. A test which covers that it works would be great ! :)

**Comment by bartosjiri** [comment]
Seems that the conditions are already isolated, now when looking at it. The existing case ([link](https://github.com/ppetzold/nestjs-paginate/blob/master/src/paginate.spec.ts#L194)) produces the following (intuitive) query:
```
... WHERE ("e"."color" = ? OR "e"."age" = ?) AND "e"."name" != ? ...
```

I am trying to identify the reason why I am getting unexpected/unisolated queries in my use case, so far unsuccessfully.

**Comment by ppetzold** [comment]
what database were you using? typeorm likely produces different sql based on db adapter

**Comment by ppetzold** [comment]
Ah okay, possible typeorm issue then. If your fix solves the problem, please add a note that this postgres specific, then the Pr is good to go ;)

Btw. merge from master please, I added some codestyle checks for ci.

**Pull request merged**
