### PR TITLE
feat: swagger annotations

### LINKED ISSUE #173: Swagger integration
It would be nice to have swagger documentation support for the parameters. Currently it's not possible to change the limit, page or filter on the docs page.

### PR DESCRIPTION
**Pull request by vsamofal**
Closes #173

Swagger annotations 

I didn't write any tests because it's not obvious how to write tests for this thing, so I checked manually. 

I will be reviewing it again tomorrow because I fill like I missed something in the schema. appreciate feedback/comments 

image
image

### CODE REVIEW

**Comment by Chrisp1tv** [comment]
Hey 👋 I've also been doing some PR around this and managed to create a test for this, I think you could have a look at it: https://github.com/ppetzold/nestjs-paginate/pull/714/files#diff-117c172add187737efd895786b1662b88894bb8ad7fb4cb1868151f766f594f9 ;)

**Comment by vsamofal** [comment]
@Chrisp1tv that's funny :) 

Yes, I think I can use your idea for tests. Let someone take a look on both prs and decide, will probably just combine them somehow

**Review by ppetzold — CHANGES_REQUESTED** [review]
hi guys :) thanks for the contribution! I think I prefer the approach here from #713 - it reuses the pagination config, so no need to keep anything in sync and it seems a bit more comprehensive - although some tests like #714 would be neat :)

**Comment by vsamofal** [comment]
@ppetzold tests are ready 

@Chrisp1tv thank you a lot for the idea with tests, you saved me sometime on research :)

**Review by ppetzold — APPROVED** [review]

**Pull request merged**
