### PR TITLE
Fix TypeError When Using @Paginate() with @MessagePattern() (@nestjs/microservices)

### PR DESCRIPTION
**Pull request by AAAAAAAAlan**
### Problem

Currently, when the `@Paginate()` decorator is used alongside the `@MessagePattern()` decorator within a NestJS microservice, an error is thrown. This occurs because `ExecutionContextHost.switchToHttp().getRequest()` does not contain a `query` key in 'rpc' mode, leading to `undefined` being returned and causing the following `TypeError`:

```
TypeError: Cannot read properties of undefined (reading 'searchBy')
```

This error specifically arises due to the incompatibility of the `@Paginate()` decorator expecting HTTP request objects in an environment where such objects are not available.

### CODE REVIEW

**Comment by Helveg** [comment]
I'm unfamiliar with RPC, could you explain why `request` instead of `request.query` is an appropriate fix?

**Comment by AAAAAAAAlan** [comment]
> I'm unfamiliar with RPC, could you explain why `request` instead of `request.query` is an appropriate fix?

While using `@MessagePattern` - `request` variable contains query parameters in itself and nothing more. Im also unfamiliar with RPC, I did some "console.logging" and found that out.

I'm not really interested in contributing or finding other, better solutions. This fix works perfectly in my project, and I just wanted to highlight the issue for maintainers and fellow gamers

**Review by Helveg — APPROVED** [review]
Finished OP's PR.

(Sort of) added (untested) WS & RCP support, assuming that their query will be in `getData()`.

**Comment by Helveg** [comment]
@ppetzold could you have a look?

**Comment by Helveg** [comment]
@ppetzold ping :)

**Review by ppetzold — APPROVED** [review]
nicely done 🚀

**Pull request merged**
