### PR TITLE
feat: multi filter with $and/$or comperator

### PR DESCRIPTION
**Pull request by xMase**
This feature introduce the operand $and and $or for a selected column (#402) and its based on pr #434. 

Example
`?filter.mycolumn=$eq:1&filter.mycolumn=$or:$eq:10 `
will be translated to:
`AND (mycolumn=1 OR mycolumn=10)`

### CODE REVIEW

**Comment by xMase** [comment]
@ppetzold i complete the merge, but the ci fail with unknown motivation. Can you check that?

**Comment by ppetzold** [comment]
`npm run format` will fix

**Comment by xMase** [comment]
i have already used it but nothing change

**Review by ppetzold — COMMENTED** [review]
Finally found some time to go through this PR. A couple of questions:

(1) As I believe we don't have coverage for this. Does no-op still default to `$eq`?
`filter.foo=bar` same as `filter.foo=$eq:bar`

(2) Is the comperator required on the second item or does no-comp default to `$and`?
The latter would be great for intuitive "shorts" like `?filter.created=$gte:2022-02-02&filter.created=$lte:2022-03-03`.
Would close #77 as well.

(3) As we don't seem to have coverage, did the decorator parse an array of filters already as string array?
Typings seem right and your tests assume so, but I am not sure whether the implementation actually does.
https://github.com/ppetzold/nestjs-paginate/blob/master/src/decorator.ts#L53
So `?filter.mycolumn=$eq:1&filter.mycolumn=$or:$eq:10`
parsed as `{mycolumn: ['$eq:1', '$or:$eq:10']}`?

I believe Express does, not sure about Fastify tho.

**Comment by ppetzold** [comment]
(4) Few usage examples on README would be great 🚀

**Comment by ppetzold** [comment]
(5) I assume order matters, what happens in the follow edge case?
`?filter.mycolumn=$or:$eq:1&filter.mycolumn=$and:$eq:10`

**Comment by ppetzold** [comment]
(6) Wdyt about comperator whitelisting? `$or` does have considerable performance impact which you may want to prevent.

**Comment by FrancYescO** [comment]
This based on my tests, idk if @xMase have more to say about

1) yes, i assume is indirectly tested by https://github.com/ppetzold/nestjs-paginate/blob/0563cc27061870f562fc7609e9a74135340f870e/src/paginate.spec.ts#L1425 otherwhise just remove the $eq from this test may be enough https://github.com/ppetzold/nestjs-paginate/blob/0563cc27061870f562fc7609e9a74135340f870e/src/paginate.spec.ts#L1127
2) defaults to `$and`, otherwise the user can be allowed to force an ever true condition to skip some "hardcoded" filters
3) yes, and you are also allowed to do also `?filter.mycolumn[0]=$eq:1&filter.mycolumn[1]=$or:$eq:10`, idk if there is a standard here, may be some HTTP RFC grayside, so i'll consider out of scope of this PR.
5) Both conditions will be putted in OR
6) Personally i think is a little out of scope here and can be really up to the implementation to restrict/allow a kind of usage, in general limiting can be easier instead of allowing, IMO from a library side i think is not good to have a whitelist-approach but as all this lib is already have all option in this way (causing hassle to revert it back to a blacklist-approach :P) can be a good thing to have.

**Comment by xMase** [comment]
(2) Is the comperator required on the second item or does no-comp default to $and?
the dafault comparator is a $and

(5) I assume order matters, what happens in the following edge case?
?filter.mycolumn=$or:$eq:1&filter.mycolumn=$and:$eq:10

yes the order meters, the first comparator will be ignored.  

```
filter.mycolumn=$or:$eq:1&filter.mycolumn=$and:$eq:10
filter.mycolumn=$and:$eq:1&filter.mycolumn=$and:$eq:10
filter.mycolumn=$eq:1&filter.mycolumn=$and:$eq:10
```
will be:
```
WHERE (...) AND (mycolumn=1 OR mycolumn=10) AND (...)
```

(4) ok i put some line on readme

(6) ok, can you take this for a future pr? (i can implement this soon, in the meantime you can validate the pr #463)

**Comment by ppetzold** [comment]
sweet, then let's address the following and then the PR is good to go:

(1) As @FrancYescO suggested adjust test below to create no-op coverage and check if your changes pass
https://github.com/ppetzold/nestjs-paginate/blob/0563cc27061870f562fc7609e9a74135340f870e/src/paginate.spec.ts#L1127

(2) Add usage example in README

**Comment by xMase** [comment]
ok, i have awarded all the changes to the PR!

**Review by ppetzold — APPROVED** [review]

**Pull request merged**
