### PR TITLE
fix: fixed a problem for uppercase fields on search by 

### LINKED ISSUE #445: searchBy throwing error in case of upper case fields for postgres
Hey Philipp!
We need to do a hotfix regarding the latest release of the package with 4.6.2.
The change introduced with #442 is now having problems with upper case variable names.

Currently already working on a fix.

Here the error...

 WHERE (\"user\".\"deleted\" = $1) AND (user.firstName::text ILIKE '%admin%' OR user.lastName::text ILIKE '%admin%' OR user.email::text ILIKE '%admin%' OR user.role::text ILIKE '%admin%')) \"distinctAlias\" ORDER BY \"distinctAlias\".\"user_lastName\" ASC, \"user_id\" ASC LIMIT 20","parameters":[false],"driverError":{"length":92,"name":"error","severity":"ERROR","code":"42601","position":"6379","file":"scan.l","line":"1180","routine":"scanner_yyerror"},"length":92,"severity":"ERROR","code":"42601","position":"6379","file":"scan.l","line":"1180","routine":"scanner_yyerror"}

### PR DESCRIPTION
**Pull request by jakobwgnr**
Hey!

This PR closes #445 

BR Jakob

### CODE REVIEW

**Review by ppetzold — APPROVED** [review]
lgtm

**Comment by jakobwgnr** [comment]
@ppetzold just tested and now working fine.

**Comment by ppetzold** [comment]
Cool :)

**Pull request merged**
