### PR TITLE
Only add NULL_SORT when the nullSort field is provided, and add more tests

### PR DESCRIPTION
**Pull request by Elbarae1921**
follow up for #296

### CODE REVIEW

**Review by ppetzold — CHANGES_REQUESTED** [review]
See https://github.com/ppetzold/nestjs-paginate/pull/296#issuecomment-1221926388

**Comment by Elbarae1921** [comment]
Fixed, now it only adds the argument if the user specifies the `nullSort` field, it's not optimal but it works for postgres at least. I think there could be a way to achieve this behavior for MySQL and SQL Server as well but it would add a lot of complexity. And I think it would be kinda beyond the scope of this project, wouldn't you agree?

**Review by ppetzold — APPROVED** [review]

**Comment by ppetzold** [comment]
> Fixed, now it only adds the argument if the user specifies the `nullSort` field, it's not optimal but it works for postgres at least. I think there could be a way to achieve this behavior for MySQL and SQL Server as well but it would add a lot of complexity. And I think it would be kinda beyond the scope of this project, wouldn't you agree?

Yup, good with me.

**Pull request merged**
