### PR TITLE
feat: basic json column support

### PR DESCRIPTION
**Pull request by orecus**
This is a basic implementation, seems to work as expected for the base case. This could solve #359.

But ideally these two things should be sorted before merging, but opening it for early feedback by @ppetzold , i'm not quite sure yet of the best approach to solve these two, so very much open for pointers or assistance.

- [x] The logic seems to break if you use `relation.jsonField.data` for instance, from my limited understanding we probably need to add an check somewhere as it seems to think `jsonField` is a related entity, which when using json it is not.
`"missing FROM-clause entry for table \"__root_relation_rel_jsonField_rel\""`
- [ ] Some more operators than `$eq`, from reading the [implementation PR](https://github.com/typeorm/typeorm/pull/9665) this seems like a limitation in TypeOrm, if I am understanding things correctly.

### CODE REVIEW

**Review by ppetzold — CHANGES_REQUESTED** [review]
if you are keen to get this released, I am okay with merging this way of basic jsonb support.

just add a jsonb README section and highlight that relations and other operators (other than FilterOperator.EQ) are not yet supported.

**Comment by orecus** [comment]
This issue mentioned above is now fixed, the issue was actually that the isJson check returned false in the case that was failing, I fixed it by passing the full column into the check and all tests now go trough.

**Comment by ppetzold** [comment]
> This issue mentioned above is now fixed, the issue was actually that the isJson check returned false so the json logic was never used for the failing test, I fixed it by passing the full column into the check and all tests now go trough.

good stuff, if you think this PR is ready to go ... please mark as ready for review.

**Pull request merged**
