### PR TITLE
fix: update searchBy query to allow searchBy on other column types than text

### LINKED ISSUE #436: Error for columns defined as enum when search
Hello ! 
I get an error when trying to search for a property defined as enum. 
I think this is the reason why: https://stackoverflow.com/questions/35072844/using-ilike-on-an-enum-in-sql

here the created SQL-Statement:
WHERE ...  OR \"user\".\"role\" ILIKE $3  ... 

	"parameters": [
		"%Admin%",
		"%Admin%",
		"%Admin%",
		"%Admin%"
	],

I received following error...
	"driverError": {
		"length": 214,
		"name": "error",
		"severity": "ERROR",
		"code": "42883",
		"hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
		"position": "3319",
		"file": "parse_oper.c",
		"line": "731",
		"routine": "op_error"
	},

image

Hope you can help here.
BR Jakob

### PR DESCRIPTION
**Pull request by jakobwgnr**
Hey !
As discussed in #436 here is my try to fix the following issues: #436, #435, #366.

The PR is split into two commits.
1. I tried to improve the code structure of paginate.ts, hope this is appreciated :)
2. The actual fix for those issues.

The tests are running through, but of course the tests are only for sqlite. 

BR Jakob

### CODE REVIEW

**Comment by ppetzold** [comment]
Cool. Happy to accept a larger code restructuring - but in a separate PR 😅 

Always good to keep commits small and not hijack what the commit message states :grimacing:

**Comment by MikiDylewski** [comment]
Heya, i wonder is there estimate how long would it take for this changes to be made?

**Comment by ppetzold** [comment]
@MikiDylewski up to @jakobwgnr 😅 I have asked to resubmit the fix without the code restructuring. would merge and release then asap

**Comment by MikiDylewski** [comment]
@ppetzold awesome, will keep eye on that then. It's really important for me as right now i have to use querybuilder, but when using it the rest of filtering doesnt apply. Thanks for the reply!

**Comment by jakobwgnr** [comment]
Hey @ppetzold @MikiDylewski will find the time this weekend!

**Comment by jakobwgnr** [comment]
@MikiDylewski please see new try with #442

**Pull request closed without merging**
